### ISSUE TITLE
Forbidden response (malwareDetected) when downloading a file

### ISSUE THREAD

**Issue by like9515** [OneDrive/onedrive-api-docs#1626]
#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

I'm trying to download a file and making the following request:
```
GET https://graph.microsoft.com/v1.0/users/:user_id/drive/items/:item_id/content
```

However, I got the error on a certain file
```
< HTTP/2 403
< cache-control: private
< content-type: text/html
< p3p: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
< x-sharepointhealthscore: 3
< docid: d131-my.sharepoint.com_b0ccbda4-ea6a-4071-a97a-d16d00bb6895_b1ab279d-812e-4910-bb9c-ab9fa5802c50
< x-aspnet-version: 4.0.30319
< x-databoundary: None
< x-1dscollectorurl: https://mobile.events.data.microsoft.com/OneCollector/1.0/
< x-ariacollectorurl: https://browser.pipe.aria.microsoft.com/Collector/3.0/
< sprequestguid: f5ee61a0-203c-d000-592f-411954a22124
< request-id: f5ee61a0-203c-d000-592f-411954a22124
< ms-cv: oGHu9TwgANBZL0EZVKIhJA.0
< strict-transport-security: max-age=31536000
< x-frame-options: SAMEORIGIN
< content-security-policy: frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com *.microsoft.com securebroker.sharepointonline.com;
< x-powered-by: ASP.NET
< microsoftsharepointteamservices: 16.0.0.22817
< x-content-type-options: nosniff
< x-ms-invokeapp: 1; RequireReadOnly
< x-cache: CONFIG_NOCACHE
< x-msedge-ref: Ref A: A22DE385D4C94557BE052FD202372754 Ref B: TPE30EDGE0521 Ref C: 2022-09-05T08:26:55Z
< date: Mon, 05 Sep 2022 08:26:55 GMT
<
* Connection #1 to host d131-my.sharepoint.com left intact
{"error":{"code":"malwareDetected","message":"Malware detected"}}
```

I'm wondering if there is a query option to skip detecting malware ?
I tried adding `AVOverride=1` mentioned in this [article](https://github.com/OneDrive/onedrive-api-docs/issues/178), but it doesn't work for me.

Thank you.

[ ]: http://aka.ms/onedrive-api-issues
[x]: http://aka.ms/onedrive-api-issues

**Comment by matt-matteis** [comment]
Any updates or workarounds for this issue?

**Comment by kashiftahir** [comment]
Thanks for posting your query. This looks like something we can explore to support on the service side.

**Comment by silikonz** [comment]
Is this resolved? I am experiencing the same issue.

**Comment by ncw** [comment]
@kashiftahir I don't think is fixed - rclone users are reporting that AVOverride=1 is not working: https://github.com/rclone/rclone/issues/7934

**Comment by AbsolutelyFreeWeb** [comment]
I believe this ticket was erroneously closed, and 2 years afterwards, it is still a problem

**Comment by oddMLan** [comment]
STILL an issue!! 3 years unfixed. Unable to download my own scripts! What's going on at Microsoft? 
Serves me right for trusting Microsoft with my own files...

**Comment by polina-di** [comment]
it is still a problem!!!

**Comment by RealRedcodi** [comment]
This is a major issue! Lots of files I needed for work just got decided they were malware, I cant figure out a way to bypass it :/ this really needs to be fixed now

**Comment by okica-11** [comment]
Agree, still a major problem!

**Comment by georgethemarmot** [comment]
Still an issue.

**Comment by qwqalu** [comment]
Still an issue.

**Comment by oddMLan** [comment]
There is an update. They restored the functionality to download malware flagged files, but you can only do it from the browser if you're the owner.
<img width="483" height="244" alt="Image" src="https://github.com/user-attachments/assets/240abfb7-1ec0-40f9-8076-a43304530670" />

Upon clicking you'll get this modal

<img width="437" height="217" alt="Image" src="https://github.com/user-attachments/assets/c378d2ba-6e37-4767-9ae4-79be9da874aa" />

Which generated the following URL
https://onedrive.live.com/personal/4033ffe769ad2354/Documents/Descargas/!TEST!/EICAR?avcmd=1

It doesn't work from the Preview/Share flow. If you right click-> select 'Preview', you get this warning

<img width="1363" height="585" alt="Image" src="https://github.com/user-attachments/assets/e971e2b5-5111-417f-b876-693c988aef24" />

Clicking download tells you it's not possible to download the file:
<img width="372" height="286" alt="Image" src="https://github.com/user-attachments/assets/2dc37902-7370-4838-ab3d-0f32e7c724b7" />

So it seems that the AVOverride flag, for all intents and purposes, is fully deprecated.
