### ISSUE TITLE
[ODP] why delta.view do not return Deleted facet

### ISSUE THREAD

**Issue by joewutaiwan** [OneDrive/onedrive-api-docs#535]
Ref : [Deleted facet](https://github.com/OneDrive/onedrive-api-docs/blob/bede978b6a9c5a107306dd779b878af387a5dcbb/facets/deleted_facet.md) 

when delete file in ODP, get delta.view response:
```
{
      "eTag": "aQ0IwQkY0MTJENTFCQkQ5RiE1NzE4Ni4x",
      "id": "CB0BF412D51BBD9F!57186",
      "lastModifiedBy": {
        "user": {
          "displayName": "cloudsync syno",
          "id": "cb0bf412d51bbd9f"
        }
      },
      "lastModifiedDateTime": "2017-03-06T06:26:15.837Z",
      "name": "file_8",
      "parentReference": {
        "driveId": "cb0bf412d51bbd9f",
        "id": "CB0BF412D51BBD9F!57143",
        "name": "2",
        "path": "/drive/root:/a/2"
      },
      "webUrl": "https://1drv.ms/u/s!AJ-9G9US9AvLg75i",
      "file": {}
    }
```
However in ODB
```
{
      "@odata.type": "#oneDrive.item",
      "@odata.id": "https://synologydst-my.sharepoint.com/_api/v2.0/drives/b!WSWlJL1W9kyaAvz7NLW_npCY43r3-FhEj6kFGpp_XlOf_XMCDYtgRIV4u2G9zBWb/items/01FLIMP2OEMFKZQUIL5NHL7OOZ6SOG6CPF",
      "@odata.editLink": "drives/b!WSWlJL1W9kyaAvz7NLW_npCY43r3-FhEj6kFGpp_XlOf_XMCDYtgRIV4u2G9zBWb/items/01FLIMP2OEMFKZQUIL5NHL7OOZ6SOG6CPF",
      "createdDateTime": "0001-01-01T00:00:00-08:00",
      "id": "01FLIMP2OEMFKZQUIL5NHL7OOZ6SOG6CPF",
      "lastModifiedDateTime": "0001-01-01T00:00:00-08:00",
      **"deleted": {
        "state": "deleted"
      },**
      "file": {},
      "parentReference": {
        "driveId": "b!WSWlJL1W9kyaAvz7NLW_npCY43r3-FhEj6kFGpp_XlOf_XMCDYtgRIV4u2G9zBWb",
        "id": "01FLIMP2JY72X63EIIPVFLKLOP5QQSWLSI"
      },
      "size": 0
    }
```

QQ, thank you for help

**Comment by verybada** [comment]
Got some problem in onedrive either.

**Comment by daboxu** [comment]
sorry guys, having a hotfix rolling out, will be back when it's deployed.

**Comment by daboxu** [comment]
it should be fixed now, please confirm it works for you.

**Comment by daboxu** [comment]
the issue should be resolved, feel free to reopen it if you are still facing this issue.

**Comment by julian-r** [comment]
Still not working for me ( delta on root folder). Thank you for your help.

**Comment by daboxu** [comment]
@julian-r how do you generate a delta token? I tested with generate a delta link by /view.delta?token=latest, delete one item, visit the delta link.
